# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tegneregelassistent_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayerStyleDialogBase(object):
    def setupUi(self, LayerStyleDialogBase):
        LayerStyleDialogBase.setObjectName("LayerStyleDialogBase")
        LayerStyleDialogBase.resize(627, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(LayerStyleDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tilte = QtWidgets.QLabel(LayerStyleDialogBase)
        self.Tilte.setObjectName("Tilte")
        self.verticalLayout.addWidget(self.Tilte)
        self.gmlTreeWidget = QtWidgets.QTreeWidget(LayerStyleDialogBase)
        self.gmlTreeWidget.setLineWidth(5)
        self.gmlTreeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.gmlTreeWidget.setColumnCount(3)
        self.gmlTreeWidget.setObjectName("gmlTreeWidget")
        self.gmlTreeWidget.headerItem().setText(0, "1")
        self.gmlTreeWidget.headerItem().setText(1, "2")
        self.gmlTreeWidget.headerItem().setText(2, "3")
        self.gmlTreeWidget.header().setVisible(True)
        self.verticalLayout.addWidget(self.gmlTreeWidget)
        self.button_box = QtWidgets.QDialogButtonBox(LayerStyleDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(LayerStyleDialogBase)
        self.button_box.accepted.connect(LayerStyleDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(LayerStyleDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LayerStyleDialogBase)

    def retranslateUi(self, LayerStyleDialogBase):
        _translate = QtCore.QCoreApplication.translate
        LayerStyleDialogBase.setWindowTitle(_translate("LayerStyleDialogBase", "Geonorge tegneregelassistent"))
        self.Tilte.setText(_translate("LayerStyleDialogBase", "GML-lag"))
